version: "3.9"
services:
  grafana:
    image: grafana/grafana
    networks:
      - backend
    volumes:
      - "./data/grafana:/var/lib/grafana"
      - "./grafana_provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
  prometheus:
    image: prom/prometheus
    networks:
      - backend
    volumes:
      - "./data/prom/data:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    expose:
      - 9090
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    volumes:
      - "./data/mysql:/var/lib/mysql"
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    networks:
      - backend
    environment:
      - DATA_SOURCE_NAME=exporter:exporterpassword@(mysql:3306)/
    expose:
      - 9104
networks:
  backend:
    driver: bridge
